<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CM.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CM\CM.csproj" />
    <ProjectReference Include="..\CM.Shared\CM.Shared.csproj" />
    <ProjectReference Include="..\..\FSAuthentication\FSAuth.Core\FSAuth.Core.csproj" />
    <ProjectReference Include="..\..\FSAuthentication\FSAuth.Server\FSAuth.Server.csproj" />
    <ProjectReference Include="..\..\FSCommon.Blazor\FSCommon.Blazor.csproj" />
    <ProjectReference Include="..\..\FSCommon.Util\FSCommon.Util.csproj" />
    <ProjectReference Include="..\..\FSDataUtil\FSDataUtil.Core\FSDataUtil.Core.csproj" />
    <ProjectReference Include="..\..\FSDataUtil\FSDataUtil.Server\FSDataUtil.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
